# SPDX-FileCopyrightText: Copyright (c) 2021-2025 Yegor Bugayenko
# SPDX-License-Identifier: MIT
---
AllCops:
  SuggestExtensions: false
  NewCops: enable
  Exclude:
    - 'venv/**/*'

Layout/EmptyLineAfterGuardClause:
  Enabled: false
Metrics/BlockLength:
  Max: 30
Layout/ElseAlignment:
  Enabled: false
Layout/EndAlignment:
  Enabled: false
Layout/IndentationWidth:
  Enabled: false
